swiftmailer:
    default_mailer: default
    mailers:
        default:
            spool:
                type: 'file'
                path: '%kernel.project_dir%/var/mailer/spool'
            transport: 'smtp'
            host: ''
            port: '587'
            encryption: 'tls'
            auth_mode: 'login'
            username: ''
            password: ''
            sender_address: '%mailer_default_sender_address%'
            stream_options:
                ssl:
                    verify_peer: false
                    verify_peer_name: false
