version: '3.1'

services:
    db:
        image: mysql:5.7
        restart: always
        volumes:
            - ./var/mysql:/var/lib/mysql
        restart: always
        container_name: symfony_mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password
        ports:
            - 3308:3306
